# Generated by Django 4.0.4 on 2022-05-13 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coolsite', '0002_alter_posts_content_alter_posts_photo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
